resolver: nightly-2016-06-12
packages:
- '.'
- ../src/hakyll/
extra-deps: []
flags:
  hakyll:
    previewServer: False
extra-package-dbs: []
# extra-include-dirs: [/path/to/dir]
# extra-lib-dirs: [/path/to/dir]
# compiler-check: newer-minor
