#!/usr/bin/env bash

############################################################
# This converts the urls with trailing .html generated by
# static site generators to clean dirctory/index.html based.
# Make sure that the urls used are absolute.
############################################################
PROJECT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )/../" && pwd )"
SITE_DIR="$PROJECT_DIR/_site"
HOST="www.rohanjain.in"

TMP_PAGE="/tmp/$RANDOM"
URL_PREFIX="href=\"/"

cd $SITE_DIR

if [ $? ]; then

    HTML_PAGES=$(find . -iname "*.html" | sed 's/^\.\///' | sed 's/.html$//')
    XML_PAGES=$(find . -iname "*.xml" | sed 's/^\.\///' | sed 's/.xml$//')

    SED_CHAIN=""
    ABS_SED_CHAIN=""


    for page in $HTML_PAGES
    do
        if [ `echo "$page" | sed 's/index$//'` ]; then
            SED_CHAIN="$SED_CHAIN | sed 's:$URL_PREFIX$page.html:$URL_PREFIX$page/:g'"
            ABS_SED_CHAIN="$ABS_SED_CHAIN | sed 's:$HOST/$page.html:$HOST/$page/:g'"
        fi
    done

    for page in $HTML_PAGES
    do
        FILENAME="$page.html"
        echo "Updating urls in $page"
        bash -c "cat $FILENAME $SED_CHAIN > $TMP_PAGE"
        if [ `echo "$page" | sed 's/index$//'` ]; then
            echo "Moving $page"
            mkdir -p "$page"
            rm $FILENAME
            FILENAME="$page/index.html"
        fi
        mv "$TMP_PAGE" "$FILENAME"

    done

    SED_CHAIN=$ABS_SED_CHAIN

    for page in $XML_PAGES
    do
        FILENAME="$page.xml"
        echo "Updating urls in $page"
        bash -c "cat $FILENAME $SED_CHAIN > $TMP_PAGE"
        mv "$TMP_PAGE" "$FILENAME"
    done
fi
