#!/usr/bin/env bash

# This hook will generate a new site in the branch where that is tracked.
# Cloned from https://gist.github.com/1002667

ERROR=0
PROJECT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )/../" && pwd )"

# git executable
_git="git"

# site generation executable
_generate="$PROJECT_DIR/scripts/regenerate.sh"

# branch from which to generate site
_origbranch="hakyll"
# branch holding the generated site
_destbranch="gh-pages"

# Find the number of uncommited, untracked or unstaged files present
CHANGED_FILES=`git status --porcelain 2>/dev/null| egrep "^(??|M| M)" | wc -l`

if [ $CHANGED_FILES -ne "0" ]; then
    echo "Changed/New files present, will stash them."
    git status --porcelain
    "$_git" add .
    "$_git" stash
fi

# directory holding the generated site -- should be excluded from vc
_site="$PROJECT_DIR/_site"

let ERROR+=$?
# the current branch
_currbranch="$(grep "^*" < <("$_git" branch) | cut -d' ' -f2)"
let ERROR+=$?

if [[ $_currbranch == $_origbranch ]]; then # we should generate the site
    echo ""
    echo "Generating Site"
    # go to root dir of the repo
    cd "$("$_git" rev-parse --show-toplevel)"
    # generate the site
    $_generate

    let ERROR+=$?
    # switch to branch the site will be stored
    "$_git" checkout "$_destbranch"
    let ERROR+=$?

    # Make sure if all the above commands are executed, so that no changes are
    # made to the master branch.
    if [ "$ERROR" -ne "0" ]; then
        echo "Errors occurred in previous commands, Won't do anything."
    else
        echo ""
        echo "Adding built site to VC."
        # overwrite existing files
        builtin shopt -s dotglob
        cp -rf "$_site"/* .
        builtin shopt -u dotglob
        # add any new files
        "$_git" add .
        # commit all changes with a default message
        "$_git" commit -a -m "updated site @ $(date +"%F %T")"
    fi

    # return
    "$_git" checkout "$_origbranch"
fi

if [ $CHANGED_FILES -ne "0" ]; then
    echo ""
    echo "Restoring the stash from changed/new files."
    "$_git" stash pop
    "$_git" reset
fi
